spiderJson = {"nodes":[
{"weight":169,"rank":19.0, "id":2, "url":"http://old.reddit.com"},
{"weight":164,"rank":4.655486071631575, "id":14, "url":"http://old.reddit.com/r/AskReddit/comments/ett7fr/what_has_been_your_biggest_fuckup_leading_up_to"},
{"weight":57,"rank":4.746382485760528, "id":20, "url":"http://old.reddit.com/domain/v.redd.it"},
{"weight":51,"rank":4.655486071631575, "id":30, "url":"http://old.reddit.com/domain/pcmag.com"},
{"weight":55,"rank":4.655486071631575, "id":41, "url":"http://old.reddit.com/r/PS4/gilded"},
{"weight":1,"rank":0.0, "id":75, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj36y5"},
{"weight":1,"rank":0.0, "id":76, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffjnmai"},
{"weight":1,"rank":0.0, "id":82, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffjkn0h"},
{"weight":1,"rank":0.0, "id":85, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffirr5u"},
{"weight":1,"rank":0.0, "id":91, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffis3rk"},
{"weight":1,"rank":0.0, "id":93, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffjlobp"},
{"weight":1,"rank":0.0, "id":94, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffjms3i"},
{"weight":1,"rank":0.0, "id":99, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffjlk8p"},
{"weight":1,"rank":0.0, "id":101, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffij6rg"},
{"weight":1,"rank":0.0, "id":109, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj40ge"},
{"weight":1,"rank":0.0, "id":115, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffiy7jn"},
{"weight":1,"rank":0.0, "id":116, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffiv3em"},
{"weight":1,"rank":0.0, "id":122, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffiqu4k"},
{"weight":1,"rank":0.0, "id":124, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffio7w3"},
{"weight":1,"rank":0.0, "id":125, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj2oiz"},
{"weight":1,"rank":0.0, "id":127, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj3hrj"},
{"weight":1,"rank":0.0, "id":128, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj4w1s"},
{"weight":1,"rank":0.0, "id":136, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj37j0"},
{"weight":1,"rank":0.0, "id":139, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffizjhi"},
{"weight":1,"rank":0.0, "id":142, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffj6z2z"},
{"weight":1,"rank":0.0, "id":143, "url":"http://old.reddit.com/gold?goldtype=gift&months=1&thing=t1_ffjatt9"}],
"links":[
{"source":0,"target":0,"value":3},
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":0,"target":3,"value":3},
{"source":0,"target":4,"value":3},
{"source":3,"target":3,"value":3},
{"source":3,"target":0,"value":3},
{"source":1,"target":1,"value":3},
{"source":1,"target":5,"value":3},
{"source":1,"target":6,"value":3},
{"source":1,"target":7,"value":3},
{"source":1,"target":8,"value":3},
{"source":1,"target":9,"value":3},
{"source":1,"target":10,"value":3},
{"source":1,"target":11,"value":3},
{"source":1,"target":12,"value":3},
{"source":1,"target":13,"value":3},
{"source":1,"target":14,"value":3},
{"source":1,"target":15,"value":3},
{"source":1,"target":16,"value":3},
{"source":1,"target":17,"value":3},
{"source":1,"target":18,"value":3},
{"source":1,"target":19,"value":3},
{"source":1,"target":20,"value":3},
{"source":1,"target":21,"value":3},
{"source":1,"target":22,"value":3},
{"source":1,"target":23,"value":3},
{"source":1,"target":24,"value":3},
{"source":1,"target":25,"value":3},
{"source":6,"target":0,"value":3},
{"source":5,"target":0,"value":3},
{"source":8,"target":0,"value":3},
{"source":12,"target":0,"value":3},
{"source":25,"target":0,"value":3},
{"source":19,"target":0,"value":3},
{"source":7,"target":0,"value":3},
{"source":10,"target":0,"value":3},
{"source":21,"target":0,"value":3},
{"source":9,"target":0,"value":3},
{"source":11,"target":0,"value":3},
{"source":20,"target":0,"value":3},
{"source":16,"target":0,"value":3},
{"source":2,"target":2,"value":3},
{"source":2,"target":0,"value":3},
{"source":17,"target":0,"value":3},
{"source":15,"target":0,"value":3},
{"source":4,"target":4,"value":3},
{"source":24,"target":0,"value":3},
{"source":22,"target":0,"value":3},
{"source":13,"target":0,"value":3},
{"source":23,"target":0,"value":3},
{"source":14,"target":0,"value":3},
{"source":18,"target":0,"value":3}]};